version: "3.9"

networks:
  localcd:

services:

  solution:
    image: ${REGISTRY}${COMPOSE_PROJECT_NAME}-solution:${VERSION:-latest}
    build:
      context: ..
      args:
        BASE_IMAGE: ${SOLUTION_BASE_IMAGE}
        BUILD_IMAGE: ${SOLUTION_BUILD_IMAGE}
        BUILD_CONFIGURATION: ${BUILD_CONFIGURATION:-Release}
        BUILD_NUMBER: ${BUILD_NUMBER}
        DEV_TOOL: ${DEV_TOOL:-None}
        TDS_Owner: ${TDS_OWNER}
        TDS_Key: ${TDS_KEY}
    scale: 0

  traefik:
    volumes:
      - ${LOCAL_TRAEFIK_PATH}:C:/etc/traefik
  
  redis:
    image: ${REGISTRY}${COMPOSE_PROJECT_NAME}-redis:${VERSION:-latest}
    build:
      context: ${LOCAL_BUILD_PATH}/redis
      args:
        BASE_IMAGE: ${SITECORE_DOCKER_REGISTRY}sitecore-redis:${SITECORE_VERSION}

  mssql:
    image: ${REGISTRY}${COMPOSE_PROJECT_NAME}-mssql:${VERSION:-latest}
    build:
      context: ${LOCAL_BUILD_PATH}/mssql
      args:
        BASE_IMAGE: ${SITECORE_DOCKER_REGISTRY}sitecore-xm1-mssql:${SITECORE_VERSION}
        SPE_IMAGE: ${SITECORE_MODULE_REGISTRY}spe-assets:${SPE_VERSION}
    mem_limit: 2GB
    volumes:
      - ${LOCAL_DATA_PATH}\mssql:c:\data

  mssql-init:
    image: ${REGISTRY}${COMPOSE_PROJECT_NAME}-mssql-init:${VERSION:-latest}
    build:
      context: ${LOCAL_BUILD_PATH}/mssql-init
      args:
        BASE_IMAGE: ${SITECORE_DOCKER_REGISTRY}sitecore-xm1-mssql-init:${SITECORE_VERSION}
        SPE_IMAGE: ${SITECORE_MODULE_REGISTRY}spe-assets:${SPE_VERSION}
        MODULE_ASSETS: ${SITECORE_MODULE_REGISTRY}spe-assets:${SPE_VERSION}
        MODULE_NAME: spe
    environment:
      DATABASES_TO_DEPLOY: spe

  mssql-init-coveo:
    image: ${REGISTRY}${COMPOSE_PROJECT_NAME}-mssql-init-coveo:${VERSION:-latest}
    build:
      context: ${LOCAL_BUILD_PATH}/mssql-init
      args:
        BASE_IMAGE: ${SITECORE_DOCKER_REGISTRY}sitecore-xm1-mssql-init:${SITECORE_VERSION}
        MODULE_ASSETS: ${COVEO_MODULE_REGISTRY}${COVEO_IMAGE}
        MODULE_NAME: coveo
    environment:
      DATABASES_TO_DEPLOY: coveo

  coveo-init:
    image: ${REGISTRY}${COMPOSE_PROJECT_NAME}-coveo-init:${VERSION:-latest}
    build:
      context: ${LOCAL_BUILD_PATH}/coveo-init
      args:
        BASE_IMAGE: ${SITECORE_DOCKER_REGISTRY}sitecore-xm1-mssql-init:${SITECORE_VERSION}
    environment:
      SITECORE_ENCRYPTION_KEY: ${SITECORE_ENCRYPTION_KEY}

  solr:
    volumes:
      - ${LOCAL_DATA_PATH}\solr:c:\data

  solr-init:
    image: ${REGISTRY}${COMPOSE_PROJECT_NAME}-solr-init:${VERSION:-latest}

    build:
      context: ${LOCAL_BUILD_PATH}/solr-init
      args:
        BASE_IMAGE: ${SITECORE_DOCKER_REGISTRY}sitecore-xm1-solr-init:${SITECORE_VERSION}
    mem_limit: 1GB


  id:
    image: ${REGISTRY}${COMPOSE_PROJECT_NAME}-id:${VERSION:-latest}
    build:
      context: ${LOCAL_BUILD_PATH}/id
      args:
        BASE_IMAGE: ${SITECORE_DOCKER_REGISTRY}sitecore-id:${SITECORE_VERSION}
    volumes:
      - ${HOST_LICENSE_FOLDER}:C:\license
    environment:
      SITECORE_LICENSE_LOCATION: C:\license\license.xml

  cd:
    image: ${REGISTRY}${COMPOSE_PROJECT_NAME}-cd:${VERSION:-latest}
    networks:
      default:
      localcd:
        aliases:
          - ${SITE_HOST}
    mem_limit: 2GB
    build:
      context: ${LOCAL_BUILD_PATH}/cd
      args:
        BASE_IMAGE: ${SITECORE_DOCKER_REGISTRY}sitecore-xm1-cd:${SITECORE_VERSION}
        TOOLING_IMAGE: ${SITECORE_TOOLS_REGISTRY}sitecore-docker-tools-assets:${TOOLS_VERSION}
        SOLUTION_IMAGE: ${REGISTRY}${COMPOSE_PROJECT_NAME}-solution:${VERSION:-latest}
        COVEO_ASSET: ${COVEO_MODULE_REGISTRY}${COVEO_IMAGE}
    depends_on:
      - solution
    volumes:
      - ${LOCAL_DEPLOY_PATH}\website:C:\deploy
      - ${LOCAL_DATA_PATH}\cd:C:\inetpub\wwwroot\App_Data\logs
      - ${HOST_LICENSE_FOLDER}:C:\license
    environment:
      SITECORE_APPSETTINGS_coveo__define: ${COVEO_ENABLE:-disabled}
      SITECORE_DEVELOPMENT_PATCHES: DevEnvOn,CustomErrorsOff,DebugOn,DiagnosticsOff,InitMessagesOff   
      SITECORE_LICENSE_LOCATION: C:\license\license.xml
      SITECORE_LOG_LEVEL: ${SITECORE_LOG_LEVEL:-INFO}
      BASIC_COMPANY_URL: ${SITE_HOST}    
      COVEO_ORG_ID:  ${COVEO_ORG_ID}
      COVEO_FARMNAME:  ${COVEO_FARMNAME}
      COVEO_API_KEY_ENCRYPTED:  ${COVEO_API_KEY_ENCRYPTED}
      COVEO_SEARCH_API_KEY_ENCRYPTED:  ${COVEO_SEARCH_API_KEY_ENCRYPTED}
      COVEO_USER:  ${COVEO_USER}
      COVEO_PASSWORD_ENCRYPTED:  ${COVEO_PASSWORD_ENCRYPTED}
    entrypoint: powershell -Command "& C:\tools\entrypoints\iis\Development.ps1"
    labels:
      - "traefik.http.routers.cd-secure.rule=Host(`${SITE_HOST}`) || Host(`${CD_HOST}`)"

  cm:
    image: ${REGISTRY}${COMPOSE_PROJECT_NAME}-cm:${VERSION:-latest}
    networks:
      default:
      localcd:
        aliases:
          - ${CM_HOST}
    mem_limit: 3GB
    build:
      context: ${LOCAL_BUILD_PATH}/cm
      args:
        BASE_IMAGE: ${SITECORE_DOCKER_REGISTRY}sitecore-xm1-cm:${SITECORE_VERSION}
        SPE_IMAGE: ${SITECORE_MODULE_REGISTRY}spe-assets:${SPE_VERSION}
        TOOLING_IMAGE: ${SITECORE_TOOLS_REGISTRY}sitecore-docker-tools-assets:${TOOLS_VERSION}
        SOLUTION_IMAGE: ${REGISTRY}${COMPOSE_PROJECT_NAME}-solution:${VERSION:-latest}
        COVEO_ASSET: ${COVEO_MODULE_REGISTRY}${COVEO_IMAGE}
    depends_on:
      - solution
    volumes:
      - ${LOCAL_DEPLOY_PATH}\website:C:\deploy
      - ${LOCAL_DATA_PATH}\cm:C:\inetpub\wwwroot\App_Data\logs
      - ${HOST_LICENSE_FOLDER}:C:\license    
    environment:
      SITECORE_APPSETTINGS_coveo__define: ${COVEO_ENABLE:-disabled}
      SITECORE_DEVELOPMENT_PATCHES: DevEnvOn,CustomErrorsOff,DebugOn,DiagnosticsOff,InitMessagesOff
      SITECORE_LICENSE_LOCATION: C:\license\license.xml
      SITECORE_LOG_LEVEL: ${SITECORE_LOG_LEVEL:-INFO}
      BASIC_COMPANY_URL: ${SITE_HOST}    
      COVEO_ORG_ID:  ${COVEO_ORG_ID}
      COVEO_FARMNAME:  ${COVEO_FARMNAME}
      COVEO_API_KEY_ENCRYPTED:  ${COVEO_API_KEY_ENCRYPTED}
      COVEO_SEARCH_API_KEY_ENCRYPTED:  ${COVEO_SEARCH_API_KEY_ENCRYPTED}
      COVEO_USER:  ${COVEO_USER}
      COVEO_PASSWORD_ENCRYPTED:  ${COVEO_PASSWORD_ENCRYPTED}
    entrypoint: powershell -Command "& C:\tools\entrypoints\iis\Development.ps1"
