version: "3.9"

services:

  solution:
    image: ${REGISTRY}${COMPOSE_PROJECT_NAME}-solution:${VERSION:-latest}
    build:
      context: ..
      args:
        BASE_IMAGE: ${SOLUTION_BASE_IMAGE}
        BUILD_IMAGE: ${SOLUTION_BUILD_IMAGE}
        BUILD_CONFIGURATION: ${BUILD_CONFIGURATION:-Release}
        TDS_Owner: ${TDS_OWNER}
        TDS_Key: ${TDS_KEY}
    scale: 0

  traefik:
    volumes:
      - ${LOCAL_TRAEFIK_PATH}:C:/etc/traefik

  mssql:
    image: ${REGISTRY}${COMPOSE_PROJECT_NAME}-mssql:${VERSION:-latest}
    build:
      context: ${LOCAL_BUILD_PATH}/mssql
      args:
        BASE_IMAGE: ${SITECORE_DOCKER_REGISTRY}sitecore-xp0-mssql:${SITECORE_VERSION}
        #SPE_IMAGE: ${SITECORE_MODULE_REGISTRY}spe-assets:${SPE_VERSION}
        #SXA_IMAGE: ${SITECORE_MODULE_REGISTRY}sxa-xp0-assets:${SXA_VERSION}
        #HORIZON_IMAGE: ${SITECORE_MODULE_REGISTRY}horizon-integration-xp0-assets:${HORIZON_ASSET_VERSION}
    mem_limit: 2GB
    volumes:
      - ${LOCAL_DATA_PATH}\mssql:c:\data
  
  # Mount our Solr data folder
  solr:
    volumes:
      - ${LOCAL_DATA_PATH}\solr:c:\data

  # Some modules (like SXA) also require additions to the Solr image.
  solr-init:
    image: ${REGISTRY}${COMPOSE_PROJECT_NAME}-solr-init:${VERSION:-latest}
    build:
      context: ${LOCAL_BUILD_PATH}/solr-init
      args:
        BASE_IMAGE: ${SITECORE_DOCKER_REGISTRY}sitecore-xp0-solr-init:${SITECORE_VERSION}
        #SXA_IMAGE: ${SITECORE_MODULE_REGISTRY}sxa-xp0-assets:${SXA_VERSION}

  id:
    image: ${REGISTRY}${COMPOSE_PROJECT_NAME}-id:${VERSION:-latest}
    build:
      context: ${LOCAL_BUILD_PATH}/id
      args:
        BASE_IMAGE: ${SITECORE_DOCKER_REGISTRY}sitecore-id:${SITECORE_VERSION}
        TOOLING_IMAGE: ${SITECORE_TOOLS_REGISTRY}sitecore-docker-tools-assets:${TOOLS_VERSION}
    depends_on:
      - solution
    volumes:
      - ${HOST_LICENSE_FOLDER}:C:\license
    environment:
      Sitecore_Sitecore__ExternalIdentityProviders__IdentityProviders__AzureAd__Enabled: ${SITECORE_ID_AZUREAD_ENABLED}
      Sitecore_Sitecore__ExternalIdentityProviders__IdentityProviders__AzureAd__ClientId: ${SITECORE_ID_AZUREAD_CLIENTID}
      Sitecore_Sitecore__ExternalIdentityProviders__IdentityProviders__AzureAd__TenantId: ${SITECORE_ID_AZUREAD_TENANTID}
      SITECORE_LICENSE_LOCATION: C:\license\license.xml
  
  cm:
    image: ${REGISTRY}${COMPOSE_PROJECT_NAME}-cm:${VERSION:-latest}
    build:
      context: ${LOCAL_BUILD_PATH}/cm
      args:
        BASE_IMAGE: ${SITECORE_DOCKER_REGISTRY}sitecore-xp0-cm:${SITECORE_VERSION}
        #SPE_IMAGE: ${SITECORE_MODULE_REGISTRY}spe-assets:${SPE_VERSION}
        #HORIZON_IMAGE: ${SITECORE_MODULE_REGISTRY}horizon-integration-xp0-assets:${HORIZON_ASSET_VERSION}
        #SXA_IMAGE: ${SITECORE_MODULE_REGISTRY}sxa-xp0-assets:${SXA_VERSION}
        TOOLING_IMAGE: ${SITECORE_TOOLS_REGISTRY}sitecore-docker-tools-assets:${TOOLS_VERSION}
        SOLUTION_IMAGE: ${REGISTRY}${COMPOSE_PROJECT_NAME}-solution:${VERSION:-latest}
    depends_on:
      - solution
    volumes:
      - ${LOCAL_DEPLOY_PATH}\website:C:\deploy
      - ${LOCAL_DATA_PATH}\cm:C:\inetpub\wwwroot\App_Data\logs
      - ${HOST_LICENSE_FOLDER}:C:\license
    environment:
      SITECORE_DEVELOPMENT_PATCHES: CustomErrorsOff
      SITECORE_LICENSE_LOCATION: C:\license\license.xml
    entrypoint: powershell -Command "& C:\tools\entrypoints\iis\Development.ps1"
      
  xconnect:
    image: ${REGISTRY}${COMPOSE_PROJECT_NAME}-xconnect:${VERSION:-latest}
    build:
      context: ${LOCAL_BUILD_PATH}/xconnect
      args:
        BASE_IMAGE: ${SITECORE_DOCKER_REGISTRY}sitecore-xp0-xconnect:${SITECORE_VERSION}
        TOOLING_IMAGE: ${SITECORE_TOOLS_REGISTRY}sitecore-docker-tools-assets:${TOOLS_VERSION}
        SOLUTION_IMAGE: ${REGISTRY}${COMPOSE_PROJECT_NAME}-solution:${VERSION:-latest}
    depends_on:
      - solution
    volumes:
      - ${HOST_LICENSE_FOLDER}:C:\license
      - ${LOCAL_DEPLOY_PATH}\xconnect:C:\deploy
    environment:
      #SITECORE_LICENSE_LOCATION: C:\license\license.xml # this doesn't work on xconnect image
      SITECORE_LICENSE_LOCATION: C:\license
    entrypoint: powershell -Command "& C:\tools\entrypoints\iis\Development.ps1"

  xdbsearchworker:
    # image: ${REGISTRY}${COMPOSE_PROJECT_NAME}-xdbsearchworker:${VERSION:-latest}
    # build:
    #   context: ${LOCAL_BUILD_PATH}/xdbsearchworker
    #   args:
    #     BASE_IMAGE: ${SITECORE_DOCKER_REGISTRY}sitecore-xp0-xdbsearchworker:${SITECORE_VERSION}
    #     SOLUTION_IMAGE: ${REGISTRY}${COMPOSE_PROJECT_NAME}-solution:${VERSION:-latest}
    depends_on:
      - solution
    volumes:
      - ${HOST_LICENSE_FOLDER}:C:\license
    environment:
      SITECORE_LICENSE_LOCATION: C:\license

  xdbautomationworker:
    # image: ${REGISTRY}${COMPOSE_PROJECT_NAME}-xdbautomationworker:${VERSION:-latest}
    # build:
    #   context: ${LOCAL_BUILD_PATH}/xdbautomationworker
    #   args:
    #     BASE_IMAGE: ${SITECORE_DOCKER_REGISTRY}sitecore-xp0-xdbautomationworker:${SITECORE_VERSION}
    #     SOLUTION_IMAGE: ${REGISTRY}${COMPOSE_PROJECT_NAME}-solution:${VERSION:-latest}
    depends_on:
      - solution
    volumes:
      - ${HOST_LICENSE_FOLDER}:C:\license
    environment:
      SITECORE_LICENSE_LOCATION: C:\license

  cortexprocessingworker:
    # image: ${REGISTRY}${COMPOSE_PROJECT_NAME}-cortexprocessingworker:${VERSION:-latest}
    # build:
    #   context: ${LOCAL_BUILD_PATH}/cortexprocessingworker
    #   args:
    #     BASE_IMAGE: ${SITECORE_DOCKER_REGISTRY}sitecore-xp0-cortexprocessingworker:${SITECORE_VERSION}
    #     SOLUTION_IMAGE: ${REGISTRY}${COMPOSE_PROJECT_NAME}-solution:${VERSION:-latest}
    depends_on:
      - solution
    volumes:
      - ${HOST_LICENSE_FOLDER}:C:\license
    environment:
      SITECORE_LICENSE_LOCATION: C:\license
