tls:
  certificates:
    - certFile: C:\etc\traefik\certs\_wildcard.helix-xp1.localhost.pem
      keyFile: C:\etc\traefik\certs\_wildcard.helix-xp1.localhost-key.pem
    - certFile: C:\etc\traefik\certs\_wildcard.helix-xp0.localhost.pem
      keyFile: C:\etc\traefik\certs\_wildcard.helix-xp0.localhost-key.pem
    - certFile: C:\etc\traefik\certs\_wildcard.helix-xm1.localhost.pem
      keyFile: C:\etc\traefik\certs\_wildcard.helix-xm1.localhost-key.pem