# This is a basic workflow to help you get started with Actions

name: Generate Build ID

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Set build ID
        id: build_id
        # add a step output `steps.build_id.outputs.id` as the unique id
        run: echo "::set-output name=id::$(date +"%Y.%-m.%-d").${GITHUB_RUN_NUMBER}"

      - name: Set build Number
        id: build_num
        run: |
          echo "::set-output name=id::$(date +"%Y.%-m.%-d").${GITHUB_RUN_NUMBER}"
          echo current build number ${{ steps.build_num.outputs.id }},          

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo here is the build number ${{ steps.build_id.outputs.id }},
          echo here is the build number ${{ steps.build_num.outputs.id }},
          echo test, and Run number ${GITHUB_RUN_NUMBER}.
