# This is a basic workflow to help you get started with Actions

name: Generate Build ID

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Set build ID
        id: build_id
        # add a step output `steps.build_id.outputs.id` as the unique id
        run: echo "::set-output name=id::$(date +"%Y.%-m.%-d").${GITHUB_RUN_NUMBER}"

      - name: Set BUILD_NUMBER ENV
      # this step set ${{ env.BUILD_NUMBER }} as the unique build number e.g. 2022.2.4.1234
        run: |
          echo "BUILD_NUMBER=$(date +"%Y.%-m.%-d").${GITHUB_RUN_NUMBER}" >> $GITHUB_ENV
          echo my build number env ${{ env.BUILD_NUMBER }}

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo the build id ${{ steps.build_id.outputs.id }},
          echo my build number env ${{ env.BUILD_NUMBER }}
