name: Docker Image CI

on:
  
  workflow_dispatch:

jobs:

  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - uses: azure/docker-login@v1
      with:
        login-server: acrsncorsc10dev.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Build docker image
      env:
        REGISTRY: acrsncorsc10dev.azurecr.io/
        COMPOSE_PROJECT_NAME: helix-xp0
        SOLUTION_BUILD_IMAGE: mcr.microsoft.com/dotnet/framework/sdk:4.8
        SOLUTION_BASE_IMAGE: mcr.microsoft.com/windows/nanoserver:1809
        BUILD_CONFIGURATION: Release
        LOCAL_BUILD_PATH: ..\docker\build
        SITECORE_DOCKER_REGISTRY: scr.sitecore.com/sxp/
        SITECORE_TOOLS_REGISTRY: scr.sitecore.com/tools/
        SITECORE_MODULE_REGISTRY: scr.sitecore.com/sxp/modules/
        SITECORE_VERSION: 10.1.1-ltsc2019
        SPE_VERSION: 6.2-1809
        TOOLS_VERSION: 10.1.0-1809
        TRAEFIK_IMAGE: traefik:v2.2.0-windowsservercore-1809
        TDS_Owner: ${{ secrets.TDS_Owner }}
        TDS_Key: ${{ secrets.TDS_Key }}
      run: | 
        docker-compose -f .\xp0\docker-compose.yml -f .\xp0\docker-compose.override.yml build
        docker-compose -f .\xp0\docker-compose.yml -f .\xp0\docker-compose.override.yml push
