name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build docker image
      run: docker-compose -f .\xp0\docker-compose.yml -f .\xp0\docker-compose.override.yml build solution
      
