name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - uses: azure/docker-login@v1
      with:
        login-server: acrsncorsc10dev.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Build docker image
      env:
        REGISTRY: acrsncorsc10dev.azurecr.io/
        COMPOSE_PROJECT_NAME: helix-xp0
        SOLUTION_BUILD_IMAGE: mcr.microsoft.com/dotnet/framework/sdk:4.8
        SOLUTION_BASE_IMAGE: mcr.microsoft.com/windows/nanoserver:1809
        BUILD_CONFIGURATION: Release
        LOCAL_DEPLOY_PATH: ..\docker\deploy
        LOCAL_DATA_PATH: ..\docker\data
        LOCAL_TRAEFIK_PATH: ..\docker\traefik
        LOCAL_BUILD_PATH: ..\docker\build
        HOST_LICENSE_FOLDER: .\install-assets
        CD_HOST: cd.helix-xp0.localhost
        CM_HOST: cm.helix-xp0.localhost
        ID_HOST: id.helix-xp0.localhost
        SITE_HOST: www.helix-xp0.localhost
        SITECORE_DOCKER_REGISTRY: scr.sitecore.com/sxp/
        SITECORE_TOOLS_REGISTRY: scr.sitecore.com/tools/
        SITECORE_MODULE_REGISTRY: scr.sitecore.com/sxp/modules/
        SITECORE_VERSION: 10.1.1-ltsc2019
        TOOLS_VERSION: 10.1.0-1809
        SPE_VERSION: 6.2-1809
        SITECORE_ADMIN_PASSWORD: ${{ secrets.SITECORE_ADMIN_PASSWORD }}
        SQL_SA_PASSWORD: ${{ secrets.SQL_SA_PASSWORD }}
        SOLR_CORE_PREFIX_NAME: sitecore
        TELERIK_ENCRYPTION_KEY: abc
        SITECORE_IDSECRET: abc
        SITECORE_ID_CERTIFICATE: abc
        SITECORE_ID_CERTIFICATE_PASSWORD: abc
        MEDIA_REQUEST_PROTECTION_SHARED_SECRET: abc
        REPORTING_API_KEY: abc
        SITECORE_LICENSE: abc
        TRAEFIK_IMAGE: traefik:v2.2.0-windowsservercore-1809
        TRAEFIK_ISOLATION: hyperv
        ISOLATION: default
        TDS_Owner: ${{ secrets.TDS_Owner }}
        TDS_Key: ${{ secrets.TDS_Key }}
      run: | 
        docker-compose -f .\xp0\docker-compose.yml -f .\xp0\docker-compose.override.yml build
        docker-compose -f .\xp0\docker-compose.yml -f .\xp0\docker-compose.override.yml push
