name: Multistage

on:
  
  workflow_dispatch:

jobs:

  build:

    environment: DEV

    runs-on: windows-2019
    
    steps:
    - uses: actions/checkout@v2

    - uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.ACR_USERNAME }}.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Build docker image
      env:
        REGISTRY: ${{ secrets.ACR_USERNAME }}.azurecr.io/
        COMPOSE_PROJECT_NAME: helix-xm1
        SOLUTION_BUILD_IMAGE: mcr.microsoft.com/dotnet/framework/sdk:4.8
        SOLUTION_BASE_IMAGE: mcr.microsoft.com/windows/nanoserver:1809
        BUILD_CONFIGURATION: Release
        DEV_TOOL: None        
        LOCAL_BUILD_PATH: ..\docker\build
        SITECORE_DOCKER_REGISTRY: scr.sitecore.com/sxp/
        SITECORE_TOOLS_REGISTRY: scr.sitecore.com/tools/
        SITECORE_MODULE_REGISTRY: scr.sitecore.com/sxp/modules/
        SITECORE_VERSION: 10.1.1-ltsc2019
        SPE_VERSION: 6.2-1809
        TOOLS_VERSION: 10.1.0-1809
        TRAEFIK_IMAGE: traefik:v2.2.0-windowsservercore-1809
        COVEO_IMAGE: custom-coveo5010391-assets:10.1.0-1809
        COVEO_MODULE_REGISTRY: ${{ secrets.ACR_USERNAME }}.azurecr.io/community/modules/
        COVEO_ENABLE: false
        TDS_Owner: ${{ secrets.TDS_Owner }}
        TDS_Key: ${{ secrets.TDS_Key }}
      working-directory: xm1
      run: | 
        docker-compose build

  publish-images:
    
    needs: [build]

    runs-on: windows-2019
        
    environment: DEV

    steps:
    - name: Login to ACR
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.ACR_USERNAME }}.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Push docker image
      env:
        REGISTRY: ${{ secrets.ACR_USERNAME }}.azurecr.io/
        COMPOSE_PROJECT_NAME: helix-xm1
        SOLUTION_BUILD_IMAGE: mcr.microsoft.com/dotnet/framework/sdk:4.8
        SOLUTION_BASE_IMAGE: mcr.microsoft.com/windows/nanoserver:1809
        BUILD_CONFIGURATION: Release
        DEV_TOOL: None        
        LOCAL_BUILD_PATH: ..\docker\build
        SITECORE_DOCKER_REGISTRY: scr.sitecore.com/sxp/
        SITECORE_TOOLS_REGISTRY: scr.sitecore.com/tools/
        SITECORE_MODULE_REGISTRY: scr.sitecore.com/sxp/modules/
        SITECORE_VERSION: 10.1.1-ltsc2019
        SPE_VERSION: 6.2-1809
        TOOLS_VERSION: 10.1.0-1809
        TRAEFIK_IMAGE: traefik:v2.2.0-windowsservercore-1809
        COVEO_IMAGE: custom-coveo5010391-assets:10.1.0-1809
        COVEO_MODULE_REGISTRY: ${{ secrets.ACR_USERNAME }}.azurecr.io/community/modules/
        COVEO_ENABLE: false
        TDS_Owner: ${{ secrets.TDS_Owner }}
        TDS_Key: ${{ secrets.TDS_Key }}
      working-directory: xm1
      run: | 
        docker-compose push

    - name: Display Status
      run: |
        echo "TODO:"
