name: Multistage

on:  
  workflow_dispatch:
    inputs:
      runson:
        type: choice
        description: 'Select Runner'
        required: true
        default: 'windows-2019'
        options:
        - windows-2019
        - self-hosted

env:
  IMAGES_TO_PUSH: helix-xm1-cd,helix-xm1-cm,helix-xm1-coveo-init,helix-xm1-id,helix-xm1-mssql,helix-xm1-mssql-init,helix-xm1-mssql-init-coveo,helix-xm1-redis,helix-xm1-solr-init,helix-xm1-solution
  BUILD_NUM_PREFIX: "1.0.0"
  
jobs:

  build:

    environment: DEV

    runs-on: ${{ github.event.inputs.runson }}
    
    steps:
    - name: Set BUILD_NUMBER
      run: |
        echo "BUILD_NUMBER=${env:BUILD_NUM_PREFIX}.${env:GITHUB_RUN_NUMBER}" >> ${env:GITHUB_ENV}

    - name: Display BUILD_NUMBER
      run: |
        echo "echo BUILD_NUMBER is ${env:BUILD_NUMBER}"

    - uses: actions/checkout@v2

    - uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.ACR_USERNAME }}.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Build docker image
      env:
        REGISTRY: ${{ secrets.ACR_USERNAME }}.azurecr.io/
        VERSION: latest
        COMPOSE_PROJECT_NAME: helix-xm1
        SOLUTION_BUILD_IMAGE: mcr.microsoft.com/dotnet/framework/sdk:4.8
        SOLUTION_BASE_IMAGE: mcr.microsoft.com/windows/nanoserver:1809
        BUILD_CONFIGURATION: Release
        DEV_TOOL: None        
        LOCAL_BUILD_PATH: ..\docker\build
        SITECORE_DOCKER_REGISTRY: scr.sitecore.com/sxp/
        SITECORE_TOOLS_REGISTRY: scr.sitecore.com/tools/
        SITECORE_MODULE_REGISTRY: scr.sitecore.com/sxp/modules/
        SITECORE_VERSION: 10.1-ltsc2019
        SPE_VERSION: 6.2-1809
        TOOLS_VERSION: 10.1.0-1809
        TRAEFIK_IMAGE: traefik:v2.2.0-windowsservercore-1809
        COVEO_IMAGE: custom-coveo5010391-assets:10.1.0-1809
        COVEO_MODULE_REGISTRY: ${{ secrets.ACR_USERNAME }}.azurecr.io/community/modules/
        TDS_Owner: ${{ secrets.TDS_Owner }}
        TDS_Key: ${{ secrets.TDS_Key }}
        CD_HOST: cd.helix.localhost
        CM_HOST: cm.helix.localhost
        ID_HOST: id.helix.localhost
        SITE_HOST: www.helix.localhost
      working-directory: xm1
      run: | 
        docker-compose build
        docker-compose push

  publish-images:
    
    needs: [build]

    runs-on: ${{ github.event.inputs.runson }}
        
    environment: DEV

    steps:
    - name: Set BUILD_NUMBER
      run: |
        echo "BUILD_NUMBER=${env:BUILD_NUM_PREFIX}.${env:GITHUB_RUN_NUMBER}" >> ${env:GITHUB_ENV}

    - name: Display BUILD_NUMBER
      run: |
        echo "echo BUILD_NUMBER is ${env:BUILD_NUMBER}"

    - name: Login to Home ACR
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.ACR_USERNAME }}.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Pull images
      run: |
        $images = ($env:IMAGES_TO_PUSH).Split(',');
        foreach ($name in $images) {
          $sourceTag = "${{ secrets.ACR_USERNAME }}.azurecr.io/$($name):latest";
          echo "docker pull $sourceTag"
          docker pull $sourceTag
        };
        docker image ls ${{ secrets.ACR_USERNAME }}.azurecr.io/*

    - name: Tag images
      run: |
        $images = ($env:IMAGES_TO_PUSH).Split(',');
        foreach ($name in $images) {
          $sourceTag = "${{ secrets.ACR_USERNAME }}.azurecr.io/$($name):latest";
          $latestTag = "${{ secrets.REMOTE_ACR_USERNAME }}.azurecr.io/$($name):latest";
          $versionTag = "${{ secrets.REMOTE_ACR_USERNAME }}.azurecr.io/$($name):${env:BUILD_NUMBER}";
          echo "docker image tag $sourceTag $latestTag"
          docker image tag $sourceTag $latestTag
          echo "docker image tag $sourceTag $versionTag"
          docker image tag $sourceTag $versionTag
        };        
        docker image ls ${{ secrets.REMOTE_ACR_USERNAME }}.azurecr.io/*

    - name: Login to Remote ACR
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.REMOTE_ACR_USERNAME }}.azurecr.io
        username: ${{ secrets.REMOTE_ACR_USERNAME }}
        password: ${{ secrets.REMOTE_ACR_PASSWORD }}

    - name: Push images to remote
      run: |
        $images = ($env:IMAGES_TO_PUSH).Split(',');
        foreach ($name in $images) {
          $latestTag = "${{ secrets.REMOTE_ACR_USERNAME }}.azurecr.io/$($name):latest";
          $versionTag = "${{ secrets.REMOTE_ACR_USERNAME }}.azurecr.io/$($name):${env:BUILD_NUMBER}";
          echo "docker push $latestTag"
          docker push $latestTag
          echo "docker push $versionTag"
          docker push $versionTag
        };