name: Create Pull Request to DevOps

on:  
  workflow_dispatch:
    inputs:
      runson:
        type: choice
        description: 'Select Runner'
        required: true
        default: 'windows-2019'
        options:
        - windows-2019
        - windows-latest
        - self-hosted

env:
  BUILD_NUMBER: 1.0.0.${{ github.run_number }}

jobs:

  build:

    environment: DEV

    runs-on: ${{ github.event.inputs.runson }}
    
    steps:
    - name: Call custom action ${{ env.BUILD_NUMBER }}
      uses: actions/devops-pullrequest
      with:
        build_number: ${{ env.BUILD_NUMBER }}

    # - name: Update docker images version to ${{ env.BUILD_NUMBER }}
    #   run: |
    #     $newbrance = "update-image-version${{ env.BUILD_NUMBER }}"
    #     $repositoryUrl = '${{ secrets.AZURE_DEVOPS_PROJECT_URL }}/_git/application'
    #     $base64PAT = [Convert]::ToBase64String([System.Text.Encoding]::UTF8.GetBytes("u:${{ secrets.AZURE_DEVOPS_TOKEN }}"))
    #     if (Test-Path $newbrance) { rm -r -fo $newbrance }
    #     git -c http.extraHeader="Authorization: Basic $base64PAT" clone $repositoryUrl $newbrance
    #     cd $newbrance
    #     git checkout -b $newbrance
    #     git config --local user.email "sitecoredev@suncor.com"
    #     git config --local user.name "Automation"        
        
    #     $ACR_NAME = "mccfmh9jpjtmdklavglacr"
    #     $VERSION = "${{ env.BUILD_NUMBER }}"
    #     $imagesJson = Get-Content .\config\docker-images\docker-images.json -raw | ConvertFrom-Json
    #     $imagesJson.sitecore.cm = "$ACR_NAME.azurecr.io/suncor-xp1-cm:$VERSION";
    #     $imagesJson.sitecore.cd = "$ACR_NAME.azurecr.io/suncor-xp1-cd:$VERSION";
    #     $imagesJson.sitecore.id = "$ACR_NAME.azurecr.io/suncor-xp1-id:$VERSION";
    #     $imagesJson.sitecore.prc = "$ACR_NAME.azurecr.io/suncor-xp1-prc:$VERSION";
    #     $imagesJson.sitecore.cortexprocessingworker = "$ACR_NAME.azurecr.io/suncor-xp1-cortexprocessingworker:$VERSION";
    #     $imagesJson.sitecore.xdbautomation = "$ACR_NAME.azurecr.io/suncor-xp1-xdbautomation:$VERSION";
    #     $imagesJson.sitecore.xdbautomationworker = "$ACR_NAME.azurecr.io/suncor-xp1-xdbautomationworker:$VERSION";
    #     $imagesJson.sitecore.xdbcollection = "$ACR_NAME.azurecr.io/suncor-xp1-xdbcollection:$VERSION";
    #     $imagesJson.sitecore.xdbsearch = "$ACR_NAME.azurecr.io/suncor-xp1-xdbsearch:$VERSION";
    #     $imagesJson.sitecore.xdbsearchworker = "$ACR_NAME.azurecr.io/suncor-xp1-xdbsearchworker:$VERSION";
    #     $imagesJson | ConvertTo-Json | Set-Content -Path .\config\docker-images\docker-images.json;
    #     git add .\config\docker-images\docker-images.json        
    #     Set-Content -Path .\config\docker-images\VERSION.md -Value '${{ env.BUILD_NUMBER }}'
    #     git add .\config\docker-images\VERSION.md
    #     echo "git commit"
    #     git commit -m"Bump image version to ${{ env.BUILD_NUMBER }}"        
    #     echo "git push"
    #     git -c http.extraHeader="Authorization: Basic $base64PAT" push --set-upstream origin $newbrance
    #     echo "creating pull request..."
    #     $uri = "${{ secrets.AZURE_DEVOPS_PROJECT_URL }}/_apis/git/repositories/application?api-version=6.0"
    #     $headers = @{
    #         'Authorization' = "Basic $base64PAT"
    #     }
    #     $repo = Invoke-RestMethod -Uri $uri -Method Get -Headers $headers
    #     $createPullRequestBody = @{
    #         sourceRefName = "refs/heads/$newbrance"
    #         targetRefName = "refs/heads/main"
    #         title = "Bump images version to ${{ env.BUILD_NUMBER }}"
    #         description = "Bump images version to ${{ env.BUILD_NUMBER }}"
    #     } | ConvertTo-Json
    #     $createPullRequestUri = "$($repo.Url)/pullrequests?api-version=6.0"
    #     Invoke-RestMethod -Uri $createPullRequestUri -Method Post -Headers $headers -Body $createPullRequestBody -ContentType 'application/json'

