name: Pull and Push

on:
  
  workflow_dispatch:

jobs:

  build:

    environment: DEV

    runs-on: windows-2019
    
    steps:
    - name: Set BUILD_NUMBER
      run: |
        echo "BUILD_NUMBER=$((get-date).ToString("yy.M.d")).${env:GITHUB_RUN_NUMBER}" >> ${env:GITHUB_ENV}

    - name: Login to Home ACR
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.ACR_USERNAME }}.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Pull images
      run: | 
        docker image pull ${{ secrets.ACR_USERNAME }}.azurecr.io/helix-xm1-redis:latest
        docker image ls ${{ secrets.ACR_USERNAME }}.azurecr.io/*

    - name: Tag images
      run: |        
        docker image tag ${{ secrets.ACR_USERNAME }}.azurecr.io/helix-xm1-redis:latest ${{ secrets.REMOTE_ACR_USERNAME }}.azurecr.io/helix-xm1-redis:latest
        docker image ls ${{ secrets.REMOTE_ACR_USERNAME }}.azurecr.io/*

    - name: Login to Remote ACR
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.REMOTE_ACR_USERNAME }}.azurecr.io
        username: ${{ secrets.REMOTE_ACR_USERNAME }}
        password: ${{ secrets.REMOTE_ACR_PASSWORD }}

    - name: Pull images
      run: | 
        docker push ${{ secrets.REMOTE_ACR_USERNAME }}.azurecr.io/helix-xm1-redis:latest