name: Pull and Push

on:
  
  workflow_dispatch:

env:
  IMAGES_TO_PUSH: helix-xm1-cd,helix-xm1-cm,helix-xm1-coveo-init,helix-xm1-id,helix-xm1-mssql,helix-xm1-mssql-init,helix-xm1-mssql-init-coveo,helix-xm1-redis,helix-xm1-solr-init,helix-xm1-solution
  BUILD_NUM_PREFIX: "1.0.0"

jobs:

  build:

    environment: DEV

    runs-on: windows-2019
    
    steps:
    - name: Set BUILD_NUMBER
      run: |
        echo "BUILD_NUMBER=${env:BUILD_NUM_PREFIX}.${env:GITHUB_RUN_NUMBER}" >> ${env:GITHUB_ENV}

    - name: Login to Home ACR
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.ACR_USERNAME }}.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Pull images
      run: |
        $images = ($env:IMAGES_TO_PUSH).Split(',');
        foreach ($name in $images) {
          $sourceTag = "${{ secrets.ACR_USERNAME }}.azurecr.io/$($name):latest";
          echo "docker pull $sourceTag"
          docker pull $sourceTag
        };
        docker image ls ${{ secrets.ACR_USERNAME }}.azurecr.io/*

    - name: Tag images
      run: |
        $images = ($env:IMAGES_TO_PUSH).Split(',');
        foreach ($name in $images) {
          $sourceTag = "${{ secrets.ACR_USERNAME }}.azurecr.io/$($name):latest";
          $latestTag = "${{ secrets.REMOTE_ACR_USERNAME }}.azurecr.io/$($name):latest";
          $versionTag = "${{ secrets.REMOTE_ACR_USERNAME }}.azurecr.io/$($name):${env:BUILD_NUMBER}";
          echo "docker image tag $sourceTag $latestTag"
          docker image tag $sourceTag $latestTag
          echo "docker image tag $sourceTag $versionTag"
          docker image tag $sourceTag $versionTag
        };        
        docker image ls ${{ secrets.REMOTE_ACR_USERNAME }}.azurecr.io/*

    - name: Login to Remote ACR
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.REMOTE_ACR_USERNAME }}.azurecr.io
        username: ${{ secrets.REMOTE_ACR_USERNAME }}
        password: ${{ secrets.REMOTE_ACR_PASSWORD }}

    - name: Push images to remote
      run: |
        $images = ($env:IMAGES_TO_PUSH).Split(',');
        foreach ($name in $images) {
          $latestTag = "${{ secrets.REMOTE_ACR_USERNAME }}.azurecr.io/$($name):latest";
          $versionTag = "${{ secrets.REMOTE_ACR_USERNAME }}.azurecr.io/$($name):${env:BUILD_NUMBER}";
          echo "docker push $latestTag"
          docker push $latestTag
          echo "docker push $versionTag"
          docker push $versionTag
        };

  publish-images:
    
    needs: [build]

    runs-on: windows-2019
        
    environment: DEV

    steps:
    - name: Display BUILD_NUMBER
      run: |
        echo "echo BUILD_NUMBER is ${env:BUILD_NUMBER}"

  