name: Pull and Push

on:
  
  workflow_dispatch:

jobs:

  build:

    environment: DEV

    runs-on: windows-2019
    
    steps:
    - name: Set BUILD_NUMBER
      run: |
        echo "BUILD_NUMBER=$((get-date).ToString("yy.M.d")).${env:GITHUB_RUN_NUMBER}" >> ${env:GITHUB_ENV}

    - name: Login to Home ACR
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.ACR_USERNAME }}.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Pull images
      run: |
        $images = @(
        'helix-xm1-cd:latest'
        'helix-xm1-cm:latest',
        'helix-xm1-coveo-init:latest',
        'helix-xm1-id:latest',
        'helix-xm1-mssql:latest',
        'helix-xm1-mssql-init:latest',
        'helix-xm1-mssql-init-coveo:latest',
        'helix-xm1-redis:latest',
        'helix-xm1-solr-init:latest',
        'helix-xm1-solution:latest');
        foreach ($name in $images) {
          docker pull "${{ secrets.ACR_USERNAME }}.azurecr.io/$($name):latest"
        };
        docker image ls ${{ secrets.ACR_USERNAME }}.azurecr.io/*

    - name: Tag images
      run: |
        $images = @(
        'helix-xm1-cd:latest'
        'helix-xm1-cm:latest',
        'helix-xm1-coveo-init:latest',
        'helix-xm1-id:latest',
        'helix-xm1-mssql:latest',
        'helix-xm1-mssql-init:latest',
        'helix-xm1-mssql-init-coveo:latest',
        'helix-xm1-redis:latest',
        'helix-xm1-solr-init:latest',
        'helix-xm1-solution:latest');
        foreach ($name in $images) {
          docker image tag "${{ secrets.ACR_USERNAME }}.azurecr.io/$($name):latest" "${{ secrets.REMOTE_ACR_USERNAME }}.azurecr.io/$($name):latest"
        };        
        docker image ls ${{ secrets.REMOTE_ACR_USERNAME }}.azurecr.io/*

    - name: Login to Remote ACR
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.REMOTE_ACR_USERNAME }}.azurecr.io
        username: ${{ secrets.REMOTE_ACR_USERNAME }}
        password: ${{ secrets.REMOTE_ACR_PASSWORD }}

    - name: Push images to remote
      run: |
        $images = @(
        'helix-xm1-cd:latest'
        'helix-xm1-cm:latest',
        'helix-xm1-coveo-init:latest',
        'helix-xm1-id:latest',
        'helix-xm1-mssql:latest',
        'helix-xm1-mssql-init:latest',
        'helix-xm1-mssql-init-coveo:latest',
        'helix-xm1-redis:latest',
        'helix-xm1-solr-init:latest',
        'helix-xm1-solution:latest');
        foreach ($name in $images) {
          docker push "${{ secrets.REMOTE_ACR_USERNAME }}.azurecr.io/$($name):latest"
        };